### PR TITLE
Feature/local dependencies

### PR DESCRIPTION
**Pull request by FeepingCreature**
Rewrite UML generation to proceed recursively, generate dependencies in the most specific applicable subpackage.

Before:

```
 package a {
     package b as a.b {}
     package c as a.c {}
 }
 a.b ..> a.c
```

After:

```
 package a {
     package b as a.b {}
     package c as a.c {}
 
     a.b ..> a.c
 }
```

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Sample output, with names removed:

```
@startuml
package A {
    package P as A.P {
        package M as A.P.M {}
    }
    package D as A.D {}
    package I as A.I {
        package E as A.I.E {}
        package J as A.I.J {}
        package R as A.I.R {}

        A.I.E ..> A.I.J
        A.I.R ..> A.I.J
    }

    A.P ..> A.D
    A.P.M ..> A.P
    A.I ..> A.I.E
    A.I ..> A.I.R
    A.I.E ..> A.P.M
    A.I.J ..> A.D
    A.I.R ..> A.P
}
package C {
    package D as C.D {}
}

A.P.M ..> C.D
@enduml
```

**Review by linkrope — CHANGES_REQUESTED** [review]
How can the dependency on "dshould" be turned into a test-only dependency?
(Now, that we have context-aware assertion error messages, why is "dshould" necessary for such a simple code?)
Replace the selective import of the "dshould" vocabulary with a global `version (unittest) import dshould;`.

**Comment by FeepingCreature** [comment]
ping?

**Comment by linkrope** [comment]
You introduced an explicit representation of the packages (`struct Node`) to simplify the output.

I wonder: can we get rid of the flags that make the code hard to read?
If we also assign the dependencies explicitly to these packages: `stuct Nodes` gets another `add` for dependencies, which stores the dependency in the `Node` of the common prefix of the client and the supplier - each without the `back`, to avoid the issue with PlantUML...

Of course, we would no longer need `written`. And we can just check `node.dependencies.empty` to find out where to place the `}`.

**Comment by FeepingCreature** [comment]
Better?

**Review by linkrope — APPROVED** [review]

**Pull request merged**
